# Base Example

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

# Getting Started

In [2]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


## Usage of Numpy

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


## Checking Numpy Version

In [4]:
import numpy as np

print(np.__version__)

2.0.2


# Creating Array

## Creating ndarray object

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


## 0-D Arrays

In [2]:
import numpy as np

arr = np.array(42)

print(arr)

42


## 1-D Array

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


## 2-D Array

In [4]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


## 3-D Array

In [5]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


## Checking Number of Dimensions

In [ ]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

## Higher Dimension Arrays

In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5], ndmin=5)

print(arr)
print('number of dimensions:', arr.ndim)

[[[[[1 2 3 4 5]]]]]
number of dimensions: 5


# Access Array Elements

## Accessing 1-D Array

In [12]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr[0])
print(arr[1])
print(arr[2] + arr[3])

1
2
7


## Accessing 2-D Arrays

In [15]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print('2nd Element on 1st row', arr[0, 1])
print('5th Element on 2nd row', arr[1, 4])

2nd Element on 1st row 2
5th Element on 2nd row 10


## Accessing 3-D Array

In [16]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


## Negative Indexing

In [17]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print("Last element from 2nd dim", arr[1, -1])

Last element from 2nd dim 10
